### ISSUE TITLE
Glue doesnt start on Xubuntu

### ISSUE THREAD

**Issue by gnouf1** [gjthompson1/glue-public#4]
When I run the software on my computer from the .AppImage it doesnt show anything into the window

![image](https://user-images.githubusercontent.com/12630623/121947778-be636a80-cd56-11eb-82bd-2182b2db553b.png)

If i use the terminal for run it I can see that :
check if server already running...
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
mesa: for the --structurizecfg-skip-uniform-regions option: may only occur zero or one times!
starting server...
Checking for update
Error: ENOENT, build/server/server.exe not found in /tmp/.mount_Glue-0dFojWx/resources/app.asar
    at createError (electron/js2c/asar_bundle.js:5:1289)
    at t.<computed> (electron/js2c/asar_bundle.js:5:2560)
    at launchServer (/tmp/.mount_Glue-0dFojWx/resources/app.asar/build/main.js:98:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async App.<anonymous> (/tmp/.mount_Glue-0dFojWx/resources/app.asar/build/main.js:165:5) {
  code: 'ENOENT',
  errno: -2
}
undefined
Update for version 0.10.0 is not available (latest version: 0.10.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null

**Comment by devcroc** [comment]
Same for me on Archlinux (Glue V 0.10.0).

Enabling the Developper Tools seems to reveal the error : 
Not Allowed to load local resources: file:///tmp/.mount_Glue...

I believe the file protocol is not allowed within Electron app, or am I missing something ?

**Comment by gjthompson1** [comment]
Yeh this is currently a known issue and needs to be fixed. Thanks for reporting it.

**Comment by fraoustin** [comment]
same error on debian

**Comment by fraoustin** [comment]
app.asar is not in /tmp/.mount_Glue-0dFojWx but in squashfs-root/resources/

**Comment by gjthompson1** [comment]
Please refer to this for a general update on this https://github.com/gjthompson1/glue-public/issues/9#issuecomment-884987402
