### ISSUE TITLE
run graph by command line

### ISSUE THREAD

**Issue by fraoustin** [gjthompson1/glue-public#8]
the main goal is to run graph by command line

sample: gluedata --graph mygraph.json 

And it's possible add environment variable

Thank

**Comment by gjthompson1** [comment]
@fraoustin Thanks for engaging with this project. Feel free to email me at 

```
print(''.join([chr(x) for x in [
        103,108,101,110,100,111,110,116,104,111,109,112,115,111,110,49,
        64,
        103,109,97,105,108,46,99,111,109
    ]
]))
```

I can directly respond to some of your questions.

**Comment by fraoustin** [comment]
Hi
I sent you a message from my email

> print(''.join([chr(x) for x in [
>         102, 114, 97, 111, 117, 115, 116, 105, 110,
>         64,
>         103, 109, 97, 105, 108, 46, 99, 111, 109
>     ]
> ]))

I am very interesting to participate to develop of this gluedata software

**Comment by gjthompson1** [comment]
Please refer to this: https://github.com/gjthompson1/glue-public/issues/9#issuecomment-884987402 for a general update which relates to this issue.

As a side note, with the API you should be able to trigger a run.
